// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SanalDepo.Api.Data;

#nullable disable

namespace SanalDepo.Api.Migrations
{
    [DbContext(typeof(SanalDepoContext))]
    partial class SanalDepoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SanalDepo.Api.Entities.Box", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BoxCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProductName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int?>("SlotId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BoxCode")
                        .IsUnique();

                    b.HasIndex("SlotId");

                    b.ToTable("Boxes");
                });

            modelBuilder.Entity("SanalDepo.Api.Entities.Rack", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WarehouseId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WarehouseId");

                    b.ToTable("Racks");
                });

            modelBuilder.Entity("SanalDepo.Api.Entities.RackLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("LevelNumber")
                        .HasColumnType("int");

                    b.Property<int>("RackId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RackId");

                    b.ToTable("RackLevels");
                });

            modelBuilder.Entity("SanalDepo.Api.Entities.Slot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RackLevelId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RackLevelId");

                    b.ToTable("Slots");
                });

            modelBuilder.Entity("SanalDepo.Api.Entities.Warehouse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Warehouses");
                });

            modelBuilder.Entity("SanalDepo.Api.Entities.Box", b =>
                {
                    b.HasOne("SanalDepo.Api.Entities.Slot", "Slot")
                        .WithMany("Boxes")
                        .HasForeignKey("SlotId");

                    b.Navigation("Slot");
                });

            modelBuilder.Entity("SanalDepo.Api.Entities.Rack", b =>
                {
                    b.HasOne("SanalDepo.Api.Entities.Warehouse", "Warehouse")
                        .WithMany("Racks")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("SanalDepo.Api.Entities.RackLevel", b =>
                {
                    b.HasOne("SanalDepo.Api.Entities.Rack", "Rack")
                        .WithMany("Levels")
                        .HasForeignKey("RackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rack");
                });

            modelBuilder.Entity("SanalDepo.Api.Entities.Slot", b =>
                {
                    b.HasOne("SanalDepo.Api.Entities.RackLevel", "RackLevel")
                        .WithMany("Slots")
                        .HasForeignKey("RackLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RackLevel");
                });

            modelBuilder.Entity("SanalDepo.Api.Entities.Rack", b =>
                {
                    b.Navigation("Levels");
                });

            modelBuilder.Entity("SanalDepo.Api.Entities.RackLevel", b =>
                {
                    b.Navigation("Slots");
                });

            modelBuilder.Entity("SanalDepo.Api.Entities.Slot", b =>
                {
                    b.Navigation("Boxes");
                });

            modelBuilder.Entity("SanalDepo.Api.Entities.Warehouse", b =>
                {
                    b.Navigation("Racks");
                });
#pragma warning restore 612, 618
        }
    }
}
